# Site settings
title: Fatec ♥ Sistemas para Internet
email: adam.macias@fatec.sp.gov.br
description: "Repositório com arquivos, aulas, provas, trabalhos, apostilas entre outras coisas relacionadas ao curso de Sistemas para Internet da Fatec Rubens Lara."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  fatechub

# URL settings
url_repository: https://github.com/adammacias/fatec-si-digital/ # https://github.com/fatechub/curso-si
url_content: content/

# Build settings
markdown: kramdown
highlighter: pygments
